[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_GOOGLE_CLIENT_ID,VITE_API_HOME,VITE_API_SEARCH,VITE_API_VIDEO,VITE_API_EXTRA,VITE_API_EXTRA2,VITE_API_EXTRA3,VITE_API_EXTRA4,VITE_API_EXTRA5,VITE_API_EXTRA6,VITE_API_EXTRA7"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
